name: Build Test

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-vue-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main' # Check out the main branch

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Build Vue App
        run: |
          # cd path/to/vue-app  # Navigate to the Vue app directory
          npm install
          npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # The build output directory
