name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: 'gh-pages'

      # cleans up the gh-pages branch before adding new content cause the asset folder will fill up otherwise
      - name: Cleanup old files in gh-pages
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git rm -rf .
          git commit -m "Cleanup old files"
          git push origin gh-pages

      - uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Build Docusaurus Docs
        run: |
          cd PBO-Docs  # Navigate to the Docusaurus directory
          npm install
          npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: PBO-Docs/build # The build output directory
          destination_dir: docs # Deploy under the /docs folder on gh-pages
          keep_files: false # clean up branach before adding new content

  deploy-vue-app:
    needs: deploy-docs # Ensure this runs after the docs deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main' # Check out the main branch

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Build Vue App
        run: |
          npm install
          npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # The build output directory
          destination_dir: app
          keep_files: true
