deploy-vue-app:
  needs: deploy-docs # Ensure this runs after the docs deployment
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main' # Check out the main branch

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Build Vue App
      run: |
        cd path/to/vue-app  # Navigate to the Vue app directory
        npm install
        npm run build

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./path/to/vue-app/dist # The build output directory
