name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger on changes to the main branch
      - docs # Trigger on changes to the docs branch

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'docs' # Check out the docs branch

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x' # Specify the Node.js version

      - name: Build Docusaurus Docs
        run: |
          cd path/to/docusaurus  # Navigate to the Docusaurus directory
          npm install
          npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./path/to/docusaurus/build # The build output directory
          destination_dir: docs # Deploy under the /docs folder on gh-pages
